import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";
import SWRProvider from "@/providers/SWRProvider";
import ToasterProvider from "@/providers/ToasterProvider";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-100">
        <SWRProvider>
          <TooltipProvider>
            <ToasterProvider />
            {children}
          </TooltipProvider>
        </SWRProvider>
      </body>
    </html>
  );
}
