import type { Metadata } from "next";
import "./globals.css";
import SWRProvider from "@/providers/SWRProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SWRProvider>
        <body>{children}</body>
      </SWRProvider>
    </html>
  );
}
